[versions]
agp = "8.2.0"
ramanujan = "1.0-SNAPSHOT"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
ext-junit = "1.1.5"
espresso-core = "3.5.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
ramanujan = { group = "in.ramanujan", name = "ramanujan-device-common", version.ref = "ramanujan" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
