package in.ramanujan.translation.codeConverter.antlr;

import in.ramanujan.enums.DataType;
import in.ramanujan.pojo.RuleEngineInput;
import in.ramanujan.pojo.ruleEngineInputUnitsExt.*;
import in.ramanujan.pojo.ruleEngineInputUnitsExt.array.Array;
import in.ramanujan.translation.codeConverter.grammar.DebugLevelCodeCreator;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.util.*;

/**
 * Python3 to Ramanujan intermediate code converter using ANTLR listener pattern.
 * <p>
 * This class extends Python3ParserBaseListener and converts Python AST nodes to the intermediate
 * representation that the Ramanujan rule engine understands. It handles Python constructs like
 * variable assignments, control flow (if/while), function definitions and calls.
 * <p>
 * The converter maintains state using stacks to handle nested constructs properly and maps
 * Python syntax to corresponding Ramanujan rule engine objects.
 * <p>
 * Example usage:
 * <pre>
 *     PythonToRamanujanConverter converter = new PythonToRamanujanConverter(
 *         ruleEngineInput, debugCreator, scope, varMap, arrayMap);
 *     // Parser will call converter methods automatically during tree walking
 * </pre>
 */
public class PythonToRamanujanConverter extends Python3ParserBaseListener {
    
    // Private fields for managing conversion state
    private final RuleEngineInput ruleEngineInput;
    private final DebugLevelCodeCreator debugLevelCodeCreator;
    private final List<String> variableScope;
    private final Map<String, Variable> variableMap;
    private final Map<String, Array> arrayMap;
    private final List<Command> commands;
    
    // Use stacks to support nested while blocks - enables proper handling of nested loops
    private final Stack<While> whileBlockStack = new Stack<>();
    private final Stack<Integer> whileStartIndexStack = new Stack<>();

    // Use stacks to support nested if blocks and else blocks - handles complex conditional logic
    private final Stack<If> ifBlockStack = new Stack<>();
    private final Stack<Integer> ifStartIndexStack = new Stack<>();
    private final Stack<Integer> elseStartIndexStack = new Stack<>();

    // Use stacks to support nested function definitions - manages function scope properly
    private final Stack<FunctionCall> funcBlockStack = new Stack<>();
    private final Stack<Integer> funcStartIndexStack = new Stack<>();

    // Track function names to IDs for function calls - enables function resolution
    private final Map<String, String> functionNameToIdMap = new HashMap<>();

    /**
     * Constructs a new PythonToRamanujanConverter with the required dependencies.
     * <p>
     * This constructor initializes all necessary state for converting Python AST to Ramanujan
     * intermediate representation. The converter will populate the provided ruleEngineInput
     * with converted elements during the parsing process.
     * <p>
     * Example usage:
     * <pre>
     *     RuleEngineInput input = new RuleEngineInput();
     *     List&lt;String&gt; scope = new ArrayList&lt;&gt;();
     *     Map&lt;String, Variable&gt; varMap = new HashMap&lt;&gt;();
     *     Map&lt;String, Array&gt; arrayMap = new HashMap&lt;&gt;();
     *
     *     PythonToRamanujanConverter converter = new PythonToRamanujanConverter(
     *         input, debugCreator, scope, varMap, arrayMap);
     * </pre>
     *
     * @param ruleEngineInput       The input object that will be populated with converted elements
     * @param debugLevelCodeCreator Optional debug code creator for generating debug output (can be null)
     * @param variableScope         List tracking current variable scope hierarchy
     * @param variableMap           Map for tracking variables by scoped name
     * @param arrayMap              Map for tracking array variables by name
     */
    public PythonToRamanujanConverter(RuleEngineInput ruleEngineInput,
                                      DebugLevelCodeCreator debugLevelCodeCreator,
                                      List<String> variableScope,
                                      Map<String, Variable> variableMap,
                                      Map<String, Array> arrayMap) {
        this.ruleEngineInput = ruleEngineInput;
        this.debugLevelCodeCreator = debugLevelCodeCreator;
        this.variableScope = variableScope;
        this.variableMap = variableMap;
        this.arrayMap = arrayMap;
        this.commands = new ArrayList<>();
    }
    
    /**
     * Returns the list of commands generated by this converter.
     * <p>
     * Example usage:
     * <pre>
     *     PythonToRamanujanConverter converter = new PythonToRamanujanConverter();
     *     List<Command> cmds = converter.getCommands();
     * </pre>
     *
     * @return List of Command objects representing the translation output.
     */
    public List<Command> getCommands() {
        return commands;
    }
    
    /**
     * Creates a new variable in the current scope and adds it to the rule engine input and variable map.
     * <p>
     * This method generates a unique variable ID based on the current scope and a random UUID, sets the variable's name,
     * data type, and value, and registers it in the rule engine input and the internal variable map for lookup.
     * <p>
     * Example usage:
     * <pre>
     *     Variable var = createVariable("x", "integer", 10);
     * </pre>
     *
     * @param name     The name of the variable to create (e.g., "x").
     * @param dataType The data type of the variable (e.g., "integer", "string").
     * @param value    The initial value to assign to the variable.
     * @return The created Variable object.
     */
    private Variable createVariable(String name, String dataType, Object value) {
        // Generate a unique variable ID using the current scope and a random UUID
        Variable variable = new Variable();
        variable.setId((variableScope.size() > 0 ? variableScope.get(variableScope.size() - 1) : "") +
                UUID.randomUUID().toString());
        variable.setName(name);
        variable.setDataType(dataType);
        variable.setValue(value);
        
        // Add the variable to the rule engine input and the variable map for lookup
        ruleEngineInput.getVariables().add(variable);
        variableMap.put(variableScope.size() > 0 ? variableScope.get(variableScope.size() - 1) + name : name, variable);

        return variable;
    }
    
    /**
     * Retrieves a variable by name from the current scope, or creates it if it does not exist.
     * <p>
     * If the variable is not found, it is automatically created with the default data type "integer" and value 0.
     * <p>
     * Example usage:
     * <pre>
     *     Variable var = getOrCreateVariable("y");
     * </pre>
     *
     * @param name The name of the variable to retrieve or create.
     * @return The existing or newly created Variable object.
     */
    private Variable getOrCreateVariable(String name) {
        // Compute the scoped variable name based on the current scope
        String scopedName = variableScope.size() > 0 ? variableScope.get(variableScope.size() - 1) + name : name;
        Variable variable = variableMap.get(scopedName);
        
        if (variable == null) {
            // Auto-create variable with integer type (default) if not found
            variable = createVariable(name, "integer", 0);
        }
        
        return variable;
    }
    
    /**
     * Creates a command representing a variable assignment operation.
     * <p>
     * This method generates a new Command object, assigns it a unique ID, and associates it with the given variable and operation ID.
     * <p>
     * Example usage:
     * <pre>
     *     Command cmd = createAssignmentCommand(variable, "assign");
     * </pre>
     *
     * @param variable    The Variable object to assign.
     * @param operationId The operation ID representing the assignment type (e.g., "assign").
     * @return The created Command object representing the assignment.
     */
    private Command createAssignmentCommand(Variable variable, String operationId) {
        Command command = new Command();
        command.setId(UUID.randomUUID().toString());
        command.setVariableId(variable.getId());
        if (operationId != null) {
            command.setOperation(operationId);
        }
        
        ruleEngineInput.getCommands().add(command);
        commands.add(command);
        
        return command;
    }
    
    /**
     * Creates an Operation object from a binary expression with the specified operator and operands.
     * <p>
     * This method generates a new Operation with a unique ID, maps the Python operator to the
     * corresponding Ramanujan operator, and sets the operands. The operation is then registered
     * in the rule engine input for later processing.
     * <p>
     * Example usage:
     * <pre>
     *     Operation op = createOperation("+", "var1", "var2");
     *     // Creates addition operation between var1 and var2
     * </pre>
     *
     * @param operator     The Python operator (e.g., "+", "-", "==", "and")
     * @param leftOperand  The left operand of the binary expression
     * @param rightOperand The right operand of the binary expression
     * @return The created Operation object with mapped operator and operands
     */
    private Operation createOperation(String operator, String leftOperand, String rightOperand) {
        // Create new operation with unique identifier
        Operation operation = new Operation();
        operation.setId(UUID.randomUUID().toString());

        // Map Python operator to Ramanujan equivalent and set operands
        operation.setOperatorType(mapPythonOperatorToRamanujan(operator));
        operation.setOperand1(leftOperand);
        operation.setOperand2(rightOperand);
        
        // Register the operation in the rule engine input
        ruleEngineInput.getOperations().add(operation);
        
        return operation;
    }
    
    /**
     * Maps Python operators to their corresponding Ramanujan rule engine operators.
     * <p>
     * This method provides the translation layer between Python syntax and Ramanujan's
     * internal operator representation. It handles arithmetic, comparison, and logical operators.
     * <p>
     * Supported mappings include:
     * - Arithmetic: +, -, *, /, //, %
     * - Comparison: ==, !=, <, <=, >, >=
     * - Logical: and (to &&), or (to ||), not (to !)
     * <p>
     * Example usage:
     * <pre>
     *     String ramanujanOp = mapPythonOperatorToRamanujan("and"); // Returns "&&"
     *     String ramanujanOp2 = mapPythonOperatorToRamanujan("//"); // Returns "/"
     * </pre>
     *
     * @param pythonOp The Python operator to map (e.g., "and", "//", "==")
     * @return The corresponding Ramanujan operator, or the original operator if no mapping exists
     */
    private String mapPythonOperatorToRamanujan(String pythonOp) {
        // Map Python operators to Ramanujan equivalents
        switch (pythonOp) {
            case "+": return "+";              // Addition
            case "-": return "-";              // Subtraction
            case "*": return "*";              // Multiplication
            case "/": return "/";              // Division
            case "//": return "/";             // Integer division maps to regular division
            case "%": return "%";              // Modulo
            case "==": return "==";            // Equality
            case "!=": return "!=";            // Inequality
            case "<": return "<";              // Less than
            case "<=": return "<=";            // Less than or equal
            case ">": return ">";              // Greater than
            case ">=": return ">=";            // Greater than or equal
            case "and": return "&&";           // Logical AND
            case "or": return "||";            // Logical OR
            case "not": return "!";            // Logical NOT
            default: return pythonOp;          // Return original if no mapping found
        }
    }
    
    
    /**
     * ANTLR listener method called when entering an expression statement in the Python AST.
     * <p>
     * This method handles variable assignments of the form "x = value". It validates that
     * function calls are not used in assignments (which is not supported), creates or retrieves
     * the target variable, parses the assigned value, and generates the appropriate command.
     * <p>
     * Supported assignment examples:
     * <pre>
     *     x = 5        # Simple integer assignment
     *     y = 3.14     # Float assignment
     *     name = "Bob" # String assignment
     * </pre>
     *
     * Unsupported (throws CompilationException):
     * <pre>
     *     x = func()   # Function call in assignment
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the expression statement
     * @throws RuntimeException If a function call is detected in the assignment
     */
    @Override
    public void enterExpr_stmt(Python3Parser.Expr_stmtContext ctx) {
        // Handle variable assignment: x = value
        if (ctx.getChildCount() >= 3 && "=".equals(ctx.getChild(1).getText())) {
            String varName = ctx.getChild(0).getText();
            String rightSide = ctx.getChild(2).getText();
            
            // Check if right side contains a function call - this is not allowed
            if (containsFunctionCall(ctx.getChild(2))) {
                throw new RuntimeException("CompilationException: Function calls in assignments like '" + varName + " = " + rightSide + "' are not supported. Use pass-by-reference: '" + rightSide.replaceAll("\\(.*\\)", "(" + varName + ")") + "' instead.");
            }

            // Get or create the variable in current scope
            Variable variable = getOrCreateVariable(varName);
            
            // Check if right side is a simple number/value
            try {
                Object value = parseValue(rightSide);
                variable.setValue(value);
                createAssignmentCommand(variable, null);
                
                // Add debug output if debug creator is available
                if (debugLevelCodeCreator != null) {
                    debugLevelCodeCreator.concat(varName + " = " + rightSide + ";");
                }
            } catch (NumberFormatException e) {
                // Right side is an expression - we'll need to handle this more complexly
                // For now, create a simple assignment command
                createAssignmentCommand(variable, null);
            }
        }
    }
    
    /**
     * Recursively checks if a parse tree node contains a function call.
     * <p>
     * This method traverses the parse tree to detect function calls, which are identified
     * by atom_expr nodes that have trailer children starting with '('. This is used to
     * enforce the rule that function calls cannot appear in assignment statements.
     * <p>
     * Example patterns detected:
     * <pre>
     *     func()           # Simple function call
     *     obj.method()     # Method call
     *     func(x, y)       # Function call with arguments
     * </pre>
     *
     * @param node The parse tree node to examine for function calls
     * @return true if the node or any of its children contains a function call, false otherwise
     */
    private boolean containsFunctionCall(org.antlr.v4.runtime.tree.ParseTree node) {
        // Check if this node is an atom_expr with a function call trailer
        if (node instanceof Python3Parser.Atom_exprContext) {
            Python3Parser.Atom_exprContext atomExpr = (Python3Parser.Atom_exprContext) node;
            // Check each trailer for function call pattern (starts with '(')
            for (Python3Parser.TrailerContext trailer : atomExpr.trailer()) {
                if (trailer.getChildCount() >= 2 && "(".equals(trailer.getChild(0).getText())) {
                    return true; // Found a function call
                }
            }
        }

        // Recursively check all children nodes
        for (int i = 0; i < node.getChildCount(); i++) {
            if (containsFunctionCall(node.getChild(i))) {
                return true;
            }
        }

        return false;
    }

    /**
     * ANTLR listener method called when entering a while statement in the Python AST.
     * <p>
     * This method handles while loop constructs by creating a While block object, parsing
     * the loop condition, and setting up tracking for commands within the loop body.
     * Uses stacks to properly handle nested while loops.
     * <p>
     * Example Python code handled:
     * <pre>
     *     while x < 10:
     *         x = x + 1
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the while statement
     */
    @Override
    public void enterWhile_stmt(Python3Parser.While_stmtContext ctx) {
        // Handle while loops: while condition:
        if (ctx.getChildCount() >= 3) {
            // Extract the condition text from the second child (after 'while')
            String conditionText = extractConditionText(ctx.getChild(1));

            // Create a While block with unique identifier
            While whileBlock = new While();
            whileBlock.setId(UUID.randomUUID().toString());

            // Parse the condition and link it to the while block
            Condition condition = parseCondition(conditionText);
            if (condition != null) {
                whileBlock.setConditionId(condition.getId());
            }

            // Store the current command count to track the starting command
            int startingCommandIndex = commands.size();

            // Add debug output for while loop start
            if (debugLevelCodeCreator != null) {
                debugLevelCodeCreator.concat("while(" + conditionText + ") {");
            }

            // Push the current while block and index onto the stack for nested loop support
            whileBlockStack.push(whileBlock);
            whileStartIndexStack.push(startingCommandIndex);

            // Register the while block in the rule engine input
            ruleEngineInput.getWhileBlocks().add(whileBlock);
        }
    }
    
    /**
     * ANTLR listener method called when exiting a while statement in the Python AST.
     * <p>
     * This method completes the while loop processing by linking the while block to its
     * starting command and cleaning up the tracking stacks. This ensures proper nesting
     * support for multiple while loops.
     *
     * @param ctx The ANTLR parse tree context for the while statement
     */
    @Override
    public void exitWhile_stmt(Python3Parser.While_stmtContext ctx) {
        // Pop the last while block and index from the stack
        if (!whileBlockStack.isEmpty() && !whileStartIndexStack.isEmpty()) {
            While whileBlock = whileBlockStack.pop();
            int startingCommandIndex = whileStartIndexStack.pop();

            // Set the starting command ID if any commands were created within this while block
            if (commands.size() > startingCommandIndex) {
                whileBlock.setWhileCommandId(commands.get(startingCommandIndex).getId());
            }
        }

        // Add debug output for while loop end
        if (debugLevelCodeCreator != null) {
            debugLevelCodeCreator.concat("}");
        }
    }
    
    /**
     * ANTLR listener method called when entering an if statement in the Python AST.
     * <p>
     * This method handles if-else constructs by creating an If block object, parsing the
     * condition, and setting up tracking for commands in both if and else branches.
     * Explicitly rejects 'elif' statements which are not supported.
     * <p>
     * Supported Python code:
     * <pre>
     *     if x > 5:
     *         y = 1
     *     else:
     *         y = 2
     * </pre>
     *
     * Unsupported (throws CompilationException):
     * <pre>
     *     elif x > 10:  # Not supported
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the if statement
     * @throws RuntimeException If 'elif' is detected in the statement
     */
    @Override
    public void enterIf_stmt(Python3Parser.If_stmtContext ctx) {
        // Check for elif: if so, throw CompilationException
        for (int i = 0; i < ctx.getChildCount(); i++) {
            if (ctx.getChild(i) instanceof TerminalNode) {
                TerminalNode terminal = (TerminalNode) ctx.getChild(i);
                if ("elif".equals(terminal.getText())) {
                    throw new RuntimeException("CompilationException: 'elif' is not supported. Use nested if-else instead.");
                }
            }
        }

        // Handle if statements: if condition: block ('else' ':' block)?
        if (ctx.getChildCount() >= 3) {
            // Extract condition from the second child (after 'if')
            String conditionText = extractConditionText(ctx.getChild(1));

            // Create if block with unique identifier
            If ifBlock = new If();
            ifBlock.setId(UUID.randomUUID().toString());

            // Parse and link the condition
            Condition condition = parseCondition(conditionText);
            if (condition != null) {
                ifBlock.setConditionId(condition.getId());
            }

            // Store the current command count to track the starting command for if block
            int startingCommandIndex = commands.size();

            // Push the current if block and index onto the stack for nested if support
            ifBlockStack.push(ifBlock);
            ifStartIndexStack.push(startingCommandIndex);

            // Check if this if statement has an else clause for later processing
            boolean hasElse = false;
            for (int i = 0; i < ctx.getChildCount(); i++) {
                if (ctx.getChild(i) instanceof TerminalNode) {
                    TerminalNode terminal = (TerminalNode) ctx.getChild(i);
                    if ("else".equals(terminal.getText())) {
                        hasElse = true;
                        // Mark where else block commands will start (placeholder, updated later)
                        elseStartIndexStack.push(-1);
                        break;
                    }
                }
            }

            if (!hasElse) {
                // No else clause, push -1 to maintain stack alignment
                elseStartIndexStack.push(-1);
            }

            // Add debug output for if statement start
            if (debugLevelCodeCreator != null) {
                debugLevelCodeCreator.concat("if(" + conditionText + ") {");
            }

            // Register the if block in the rule engine input
            ruleEngineInput.getIfBlocks().add(ifBlock);
        }
    }

    /**
     * ANTLR listener method called when exiting an if statement in the Python AST.
     * <p>
     * This method completes the if-else processing by linking the if block to its
     * commands and handling debug output. It properly manages the stacks used for
     * tracking nested if statements.
     *
     * @param ctx The ANTLR parse tree context for the if statement
     */
    @Override
    public void exitIf_stmt(Python3Parser.If_stmtContext ctx) {
        // Pop the last if block and indices from the stacks
        if (!ifBlockStack.isEmpty() && !ifStartIndexStack.isEmpty() && !elseStartIndexStack.isEmpty()) {
            If ifBlock = ifBlockStack.pop();
            int ifStartingCommandIndex = ifStartIndexStack.pop();
            int elseStartingCommandIndex = elseStartIndexStack.pop();

            // Set the command ID for the if block
            if (commands.size() > ifStartingCommandIndex) {
                ifBlock.setIfCommand(commands.get(ifStartingCommandIndex).getId());
            }

            // Set the else command ID if there was an else block
            if (elseStartingCommandIndex != -1 && elseStartingCommandIndex < commands.size()) {
                ifBlock.setElseCommandId(commands.get(elseStartingCommandIndex).getId());
            }
        }

        // Add appropriate debug output based on whether there's an else clause
        if (debugLevelCodeCreator != null) {
            boolean hasElse = false;
            // Check if this if statement has an else clause
            for (int i = 0; i < ctx.getChildCount(); i++) {
                if (ctx.getChild(i) instanceof TerminalNode) {
                    TerminalNode terminal = (TerminalNode) ctx.getChild(i);
                    if ("else".equals(terminal.getText())) {
                        hasElse = true;
                        break;
                    }
                }
            }
            if (hasElse) {
                debugLevelCodeCreator.concat("} else {");
                debugLevelCodeCreator.concat("}");
            } else {
                debugLevelCodeCreator.concat("}");
            }
        }
    }
    
    /**
     * ANTLR listener method called when entering a block in the Python AST.
     * <p>
     * This method detects when we're entering an else block by checking the context
     * and updates the tracking stacks accordingly. It handles else blocks for both
     * if statements and while loops (though while-else is noted but not fully implemented).
     * <p>
     * Example detection:
     * <pre>
     *     if condition:
     *         # if block
     *     else:
     *         # this block is detected here
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the block
     */
    @Override
    public void enterBlock(Python3Parser.BlockContext ctx) {
        // Check if this block is part of an else clause in an if statement
        if (ctx.getParent() instanceof Python3Parser.If_stmtContext) {
            Python3Parser.If_stmtContext ifCtx = (Python3Parser.If_stmtContext) ctx.getParent();

            boolean isElseBlock = isElseBlockInContext(ifCtx, ctx);

            if (isElseBlock && !elseStartIndexStack.isEmpty()) {
                // Update the else start index in the stack (replace the placeholder -1)
                elseStartIndexStack.pop();
                elseStartIndexStack.push(commands.size());
            }
        }
        // Check if this block is part of an else clause in a while statement
        else if (ctx.getParent() instanceof Python3Parser.While_stmtContext) {
            Python3Parser.While_stmtContext whileCtx = (Python3Parser.While_stmtContext) ctx.getParent();

            boolean isElseBlock = isElseBlockInContext(whileCtx, ctx);

            if (isElseBlock) {
                // For while loops, we might need to handle else blocks differently
                // Since we're not currently tracking while-else blocks, we can add that logic here
                // For now, just log or handle as needed
                if (debugLevelCodeCreator != null) {
                    debugLevelCodeCreator.concat("/* while-else block detected */");
                }
            }
        }
    }

    /**
     * Helper method to determine if a block is an else block in the given context.
     * <p>
     * This method analyzes the parse tree structure to identify else blocks by looking
     * for the pattern: 'else' ':' block. It checks if the given block follows an 'else'
     * token in the parent context.
     * <p>
     * Algorithm:
     * 1. Find the position of the block in the parent's children
     * 2. Look backwards for an 'else' token before this block
     * 3. Handle intervening ':' tokens as expected syntax
     *
     * @param parentCtx The parent context containing the potential else block
     * @param blockCtx  The block to check if it's an else block
     * @return true if this block is an else block, false otherwise
     */
    private boolean isElseBlockInContext(org.antlr.v4.runtime.tree.ParseTree parentCtx, Python3Parser.BlockContext blockCtx) {
        // Look for the pattern: 'else' ':' block
        // We need to check if this block comes after an 'else' token
        boolean isElseBlock = false;
        int blockIndex = -1;

        // Find which child this block is
        for (int i = 0; i < parentCtx.getChildCount(); i++) {
            if (parentCtx.getChild(i) == blockCtx) {
                blockIndex = i;
                break;
            }
        }

        // Check if there's an 'else' token before this block
        if (blockIndex > 1) {
            for (int i = blockIndex - 1; i >= 0; i--) {
                if (parentCtx.getChild(i) instanceof TerminalNode) {
                    TerminalNode terminal = (TerminalNode) parentCtx.getChild(i);
                    if ("else".equals(terminal.getText())) {
                        isElseBlock = true;
                        break;
                    } else if (":".equals(terminal.getText())) {
                        // Continue looking for 'else' before ':'
                        continue;
                    } else {
                        // Hit something else, not an else block
                        break;
                    }
                }
            }
        }

        return isElseBlock;
    }

    /**
     * ANTLR listener method called when entering a function definition in the Python AST.
     * <p>
     * This method handles function definitions by creating a FunctionCall object (which
     * represents the function template), setting up a new variable scope for the function,
     * and tracking the function for later resolution of function calls.
     * <p>
     * Example Python code handled:
     * <pre>
     *     def myFunction(param1, param2):
     *         # function body
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the function definition
     */
    @Override
    public void enterFuncdef(Python3Parser.FuncdefContext ctx) {
        // Handle function definition: def func_name(params):
        if (ctx.getChildCount() >= 4) {
            // Extract function name from the second child (after 'def')
            String funcName = ctx.getChild(1).getText();

            // Create a function call structure (represents the function template)
            FunctionCall functionCall = new FunctionCall();
            functionCall.setId(UUID.randomUUID().toString());

            // Track starting command index for function body
            int startingCommandIndex = commands.size();
            funcBlockStack.push(functionCall);
            funcStartIndexStack.push(startingCommandIndex);

            // Add new scope for function - parameters will be processed by enterTfpdef
            variableScope.add(functionCall.getId());

            // Register the function in the rule engine input
            ruleEngineInput.getFunctionCalls().add(functionCall);

            // Map function name to its ID for later resolution during function calls
            functionNameToIdMap.put(funcName, functionCall.getId());

            // Add debug output for function definition start
            if (debugLevelCodeCreator != null) {
                debugLevelCodeCreator.concat("def " + funcName + "() {");
            }
        }
    }
    
    /**
     * ANTLR listener method called when entering a function parameter definition in the Python AST.
     * <p>
     * This method handles individual function parameters by creating Variable objects
     * in the current function scope. It's called automatically by the ParseTreeWalker
     * for each parameter in a function definition.
     * <p>
     * Example Python code handled:
     * <pre>
     *     def func(param1, param2):  # Creates variables for param1 and param2
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the function parameter definition
     */
    @Override
    public void enterTfpdef(Python3Parser.TfpdefContext ctx) {
        // Handle function parameter definitions
        // This is called automatically by ParseTreeWalker for each parameter
        if (ctx.name() != null) {
            String paramName = ctx.name().getText();
            // Create parameter as a variable in current function scope with default integer type
            createVariable(paramName, "integer", null);
        }
    }

    /**
     * ANTLR listener method called when exiting a function definition in the Python AST.
     * <p>
     * This method completes function definition processing by linking the function to its
     * starting command, removing the function scope, and cleaning up the tracking stacks.
     *
     * @param ctx The ANTLR parse tree context for the function definition
     */
    @Override
    public void exitFuncdef(Python3Parser.FuncdefContext ctx) {
        // Pop function definition and starting index from stacks
        if (!funcBlockStack.isEmpty() && !funcStartIndexStack.isEmpty()) {
            FunctionCall functionCall = funcBlockStack.pop();
            int startingCommandIndex = funcStartIndexStack.pop();

            // Set the starting command ID for function entry
            if (commands.size() > startingCommandIndex) {
                functionCall.setCommandId(commands.get(startingCommandIndex).getId());
            }
        }

        // Remove function scope from the scope stack
        if (variableScope.size() > 0) {
            variableScope.remove(variableScope.size() - 1);
        }

        // Add debug output for function definition end
        if (debugLevelCodeCreator != null) {
            debugLevelCodeCreator.concat("}");
        }
    }
    
    /**
     * ANTLR listener method called when entering an atom expression in the Python AST.
     * <p>
     * This method detects and handles function calls by examining atom expressions that
     * have function call trailers (parentheses). It creates FunctionCall objects, resolves
     * function references, processes arguments, and generates the appropriate commands.
     * <p>
     * Example Python code handled:
     * <pre>
     *     func()           # Simple function call
     *     func(x, y)       # Function call with arguments
     *     obj.method()     # Method call (though objects not fully supported)
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the atom expression
     */
    @Override
    public void enterAtom_expr(Python3Parser.Atom_exprContext ctx) {
        // Check if this is a function call: atom followed by '(' trailer
        if (ctx.getChildCount() >= 2) {
            // Get the atom (function name)
            Python3Parser.AtomContext atomCtx = ctx.atom();

            // Check if we have trailers - there can be multiple trailers for chained calls
            for (Python3Parser.TrailerContext trailer : ctx.trailer()) {
                // Check if this trailer is a function call (starts with '(' and ends with ')')
                if (trailer.getChildCount() >= 3 && "(".equals(trailer.getChild(0).getText()) &&
                    ")".equals(trailer.getChild(trailer.getChildCount() - 1).getText())) {

                    // Extract function name from atom
                    String functionName = null;
                    if (atomCtx.name() != null) {
                        functionName = atomCtx.name().getText();
                    }

                    if (functionName != null) {
                        // Create function call object
                        FunctionCall functionCall = new FunctionCall();
                        functionCall.setId(UUID.randomUUID().toString());

                        // Set the function ID if we know this function (from function definitions)
                        String functionId = functionNameToIdMap.get(functionName);
                        if (functionId != null) {
                            // This links to a previously defined function
                            functionCall.setFunctionId(functionId);
                        } else {
                            // Unknown function - might be external or built-in
                            functionCall.setFunctionId(functionName); // Use name as fallback
                        }

                        // Parse and resolve arguments
                        List<String> argumentIds = new ArrayList<>();
                        Python3Parser.ArglistContext arglist = trailer.arglist();
                        if (arglist != null) {
                            // Process each argument in the argument list
                            for (Python3Parser.ArgumentContext argCtx : arglist.argument()) {
                                String argText = argCtx.getText();
                                // Try to resolve argument as variable or literal
                                String argumentId = resolveArgument(argText);
                                argumentIds.add(argumentId);
                            }
                        }

                        functionCall.setArguments(argumentIds);

                        // Create a command for this function call
                        Command command = new Command();
                        command.setId(UUID.randomUUID().toString());
                        command.setFunctionCall(functionCall);

                        // Register the command and function call in rule engine input
                        ruleEngineInput.getCommands().add(command);
                        commands.add(command);
                        ruleEngineInput.getFunctionCalls().add(functionCall);

                        // Add debug output for function call
                        if (debugLevelCodeCreator != null) {
                            StringBuilder args = new StringBuilder();
                            for (int i = 0; i < argumentIds.size(); i++) {
                                if (i > 0) args.append(", ");
                                args.append(argumentIds.get(i));
                            }
                            debugLevelCodeCreator.concat("exec " + functionName + "(" + args + ");");
                        }
                    }
                }
            }
        }
    }

    /**
     * Resolves a function argument to either a variable ID or a literal value.
     * <p>
     * This method attempts to resolve function arguments by first checking if they
     * correspond to existing variables, and if not, treating them as literal values.
     * This enables functions to be called with both variable references and direct values.
     * <p>
     * Resolution priority:
     * 1. Check if argument matches an existing variable name
     * 2. Try to parse as a literal value (number, string)
     * 3. Return as-is if neither above applies
     * <p>
     * Example usage:
     * <pre>
     *     String id1 = resolveArgument("x");     // Returns variable ID if x exists
     *     String id2 = resolveArgument("42");    // Returns "42" as literal
     *     String id3 = resolveArgument("\"hi\""); // Returns "\"hi\"" as string literal
     * </pre>
     *
     * @param argText The argument text to resolve
     * @return The variable ID if the argument is a variable, or the literal value otherwise
     */
    private String resolveArgument(String argText) {
        // Try to find it as a variable first
        Variable variable = getOrCreateVariable(argText);
        if (variable != null) {
            return variable.getId();
        }

        // If it's a literal, return as-is
        try {
            parseValue(argText);
            return argText; // It's a valid literal
        } catch (NumberFormatException e) {
            // Not a simple literal, return as variable reference
            return argText;
        }
    }

    /**
     * Parses a string value into the appropriate Java object type.
     * <p>
     * This method attempts to parse string representations of values into their
     * corresponding Java types. It tries integer first, then double, and finally
     * treats the value as a string (removing quotes if present).
     * <p>
     * Parsing priority:
     * 1. Integer (e.g., "42" -> Integer(42))
     * 2. Double (e.g., "3.14" -> Double(3.14))
     * 3. String (e.g., "\"hello\"" -> "hello", "'world'" -> "world")
     * <p>
     * Example usage:
     * <pre>
     *     Object val1 = parseValue("42");        // Returns Integer(42)
     *     Object val2 = parseValue("3.14");      // Returns Double(3.14)
     *     Object val3 = parseValue("\"hello\""); // Returns String("hello")
     * </pre>
     *
     * @param valueStr The string representation of the value to parse
     * @return The parsed value as Integer, Double, or String
     * @throws NumberFormatException If the value cannot be parsed as a number and is not a valid string
     */
    private Object parseValue(String valueStr) throws NumberFormatException {
        valueStr = valueStr.trim();
        
        // Try integer parsing first
        try {
            return Integer.parseInt(valueStr);
        } catch (NumberFormatException e1) {
            // Try double parsing
            try {
                return Double.parseDouble(valueStr);
            } catch (NumberFormatException e2) {
                // Return as string (remove quotes if present)
                if (valueStr.startsWith("\"") && valueStr.endsWith("\"")) {
                    return valueStr.substring(1, valueStr.length() - 1);
                } else if (valueStr.startsWith("'") && valueStr.endsWith("'")) {
                    return valueStr.substring(1, valueStr.length() - 1);
                }
                return valueStr;
            }
        }
    }
    
    /**
     * Recursively extracts condition text from a parse tree node.
     * <p>
     * This method traverses the parse tree to extract the textual representation
     * of a condition expression. It handles both terminal nodes (direct text) and
     * non-terminal nodes (by recursively extracting from children).
     * <p>
     * Example usage:
     * <pre>
     *     String condition = extractConditionText(conditionNode);
     *     // For "x < 5", returns "x<5"
     *     // For "a == b and c > d", returns "a==bandc>d"
     * </pre>
     *
     * @param node The parse tree node from which to extract condition text
     * @return The concatenated text representation of the condition
     */
    private String extractConditionText(org.antlr.v4.runtime.tree.ParseTree node) {
        // Handle terminal nodes (leaf nodes with direct text)
        if (node instanceof TerminalNode) {
            return node.getText();
        }
        
        // Handle non-terminal nodes by recursively processing children
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < node.getChildCount(); i++) {
            sb.append(extractConditionText(node.getChild(i)));
        }
        return sb.toString();
    }
    
    /**
     * Parses a condition string and creates a corresponding Condition object.
     * <p>
     * This method analyzes condition text to identify comparison operators and creates
     * Condition objects for the rule engine. It handles various comparison operators
     * with precedence given to longer operators (e.g., "<=" before "<").
     * <p>
     * Supported operators (in precedence order):
     * - "<=", ">=" (compound operators first)
     * - "==", "!=" (equality operators)
     * - "<", ">" (simple comparison operators)
     * <p>
     * Example usage:
     * <pre>
     *     Condition cond1 = parseCondition("x<=5");  // Creates less-than-or-equal condition
     *     Condition cond2 = parseCondition("a==b");  // Creates equality condition
     * </pre>
     *
     * @param conditionText The condition text to parse (e.g., "x<5", "a==b")
     * @return A Condition object representing the parsed condition, or null if no operator found
     */
    private Condition parseCondition(String conditionText) {
        // Simple condition parsing - look for comparison operators
        // Order matters: check longer operators first to avoid partial matches
        String[] operators = {"<=", ">=", "==", "!=", "<", ">"};

        for (String op : operators) {
            if (conditionText.contains(op)) {
                // Split on the operator, limiting to 2 parts
                String[] parts = conditionText.split(op, 2);
                if (parts.length == 2) {
                    // Create condition object with unique identifier
                    Condition condition = new Condition();
                    condition.setId(UUID.randomUUID().toString());

                    // Set condition properties
                    condition.setConditionType(mapPythonOperatorToRamanujan(op));
                    condition.setComparisionCommand1(parts[0].trim());
                    condition.setComparisionCommand2(parts[1].trim());

                    // Register condition in rule engine input
                    ruleEngineInput.getConditions().add(condition);
                    return condition;
                }
            }
        }

        return null; // No supported operator found
    }

    /**
     * ANTLR listener method called when entering a return statement in the Python AST.
     * <p>
     * This method enforces the rule that return statements are not supported in the
     * Ramanujan system. Instead, functions should use pass-by-reference parameters
     * to communicate results back to callers.
     * <p>
     * Unsupported Python code (throws CompilationException):
     * <pre>
     *     def func():
     *         return 42  # This will throw an exception
     * </pre>
     *
     * Recommended alternative:
     * <pre>
     *     def func(result):
     *         result = 42  # Use pass-by-reference instead
     * </pre>
     *
     * @param ctx The ANTLR parse tree context for the return statement
     * @throws RuntimeException Always thrown to indicate return statements are not supported
     */
    @Override
    public void enterReturn_stmt(Python3Parser.Return_stmtContext ctx) {
        // Throw compilation exception for return statements
        throw new RuntimeException("CompilationException: 'return' statements are not supported. Functions should use pass-by-reference parameters instead.");
    }
}

